name: treasure Tests

on:
  push:
    branches: [main, dev] # 当推送到 main 或 dev 分支时触发
  pull_request:
    branches: [main, dev] # PR 触发

jobs:
  test:
    runs-on: ubuntu-latest # 运行环境

    steps:
      # 检查代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4 #  Go 版本

      # 3.安装依赖
      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      # 4. 运行测试
      - name: Run tests
        run: go test -v ./...

      - name: Lint code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...
